# Generated by Django 3.2.25 on 2025-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_auto_20250220_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
