# Generated by Django 3.2.25 on 2025-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_blog_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
