# Generated by Django 3.2.25 on 2025-02-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('productApp', '0007_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='addedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.profile'),
            preserve_default=False,
        ),
    ]
