# Generated by Django 3.2.25 on 2025-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0008_blog_addedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='price',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('dessert', 'Dessert'), ('main_course', 'Main Course'), ('appetizer', 'Appetizer'), ('beverage', 'Beverage')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
